### ISSUE TITLE
There is a bug in the framework where trying to dispose and removing the animation controller

### ISSUE THREAD

**Issue by BRZErez** [rajajain08/particles_flutter#1]
when using multiple pages app, moving form one page to the other will call the dispose method in your framework.
This can't be done. Calling awayAnimationController.dispose(); will cause an exception that trying to dispose on null.

When removing this line (Need to dispose the controller of course but this is OK!) everything is working.
But you can't dispose the animation controller.

Solution:

`@override
  void dispose() {
    controller.dispose();
    super.dispose();
  }`

Hopefully this helped lots of other developers that has the same issue.
Other then that, grate framework!
10x

**Comment by madhavtripathi05** [comment]
just add null checks:
```dart
@override 
void dispose() {
 awayAnimationController?.dispose();
 controller?.dispose(); 
 super.dispose(); 
}
```
