### ISSUE TITLE
Separate Particle and Line Color

### ISSUE THREAD

**Issue by PieterPicup** [rajajain08/particles_flutter#2]
Would you be open to adding a new color for the lines joining the particles?

I have used the Original web and android versions of Particle libs and they have that as a feature.
It would be great to have it in this lib.

I could always do it and create a PR for you?

**Comment by rajajain08** [comment]
Yup! You can.

**Comment by Alexspriet** [comment]
Hi @PieterPicup, did you manage to do it?
Cheers

**Comment by PieterPicup** [comment]
Hi @Alexspriet 
I have done it locally after importing the lib into my project.
I have not had a chance to make a PR as I am not on the project at this point it time anymore.
I will only be getting back to that project in late august.

It was really simple to follow the same pattern as the particle color and add a line color variable down to the painter.

Regards
