### ISSUE TITLE
Any Plans for Null-Safety ?

### ISSUE THREAD

**Issue by stonekase** [rajajain08/particles_flutter#3]
Hi there , great work on this library. Any plans for a null-safety version?

**Comment by br-programmer** [comment]
I will migrate it and send a PR

**Comment by rajajain08** [comment]
Hi @stonekase , I'm not getting enough time to work on it. Thanks, @br-programmer, I'll review and publish it ASAP!

**Comment by rajajain08** [comment]
Published!!
