### ISSUE TITLE
setState() called after dispose()` error when upgrading from version 0.1.4

### ISSUE THREAD

**Issue by albint3r** [rajajain08/particles_flutter#9]
**Issue: `setState() called after dispose()` error when upgrading to the latest version of `particles_flutter`**

**Description:**

I was using the library version `particles_flutter: ^0.1.4` without any issues. However, after upgrading to the latest version, I encountered the following error:

```
setState() called after dispose(): _ParticlesState#XXXXXX(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree.
```

This error appears when using the `Particles` widget within a `StatefulWidget` that gets disposed. The error message suggests that `setState()` is being called after the widget has been removed from the widget tree, which might indicate that the internal state management in the library is not properly checking the widget's `mounted` status before calling `setState()`.

**Steps to Reproduce:**
1. Use `particles_flutter: ^0.1.4` in a `StatefulWidget` with animations or frequent updates.
2. Upgrade to the latest version of the library.
3. Observe the error upon widget disposal.

**Expected Behavior:**

No error should be thrown after upgrading to the new version. The library should check if the widget is still mounted before calling `setState()` to prevent this issue.

**Workaround:**

For now, I have decided to revert to version `particles_flutter: ^0.1.4`, where this issue does not occur.

**Environment:**
- Flutter version: [Your Flutter version]
- particles_flutter version: [Latest version]
- Platform: [iOS, Android, Web]

Please let me know if you need further details or additional logs. I hope this issue can be resolved soon so I can use the latest version of the library.

Thank you for your hard work!

**Comment by rajajain08** [comment]
Hey, Thanks for raising the issue with complete information. I have resolved the issue and published the same on pub.dev with version 1.0.1.
